"""hospedaje: habitacion, huesped, reserva

Revision ID: 0d808265c773
Revises: d4281ab405f0
Create Date: 2026-08-06 20:05:51.266771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d808265c773'
down_revision: Union[str, None] = 'd4281ab405f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habitacion',
    sa.Column('id_habitacion', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=10), nullable=False),
    sa.Column('piso', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('DISPONIBLE', 'OCUPADA', 'LIMPIEZA', 'MANTENIMIENTO', name='estado_habitacion', native_enum=False), server_default='DISPONIBLE', nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_habitacion'),
    schema='hotel'
    )
    op.create_index(op.f('ix_hotel_habitacion_numero'), 'habitacion', ['numero'], unique=True, schema='hotel')
    op.create_table('huesped',
    sa.Column('id_huesped', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('cedula', sa.String(length=30), nullable=False),
    sa.Column('contacto', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=20), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_huesped'),
    schema='hotel'
    )
    op.create_index(op.f('ix_hotel_huesped_cedula'), 'huesped', ['cedula'], unique=True, schema='hotel')
    op.create_table('reserva',
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('id_habitacion', sa.Integer(), nullable=False),
    sa.Column('id_huesped', sa.Integer(), nullable=False),
    sa.Column('fecha_checkin_prevista', sa.Date(), nullable=False),
    sa.Column('fecha_checkout_prevista', sa.Date(), nullable=False),
    sa.Column('fecha_checkin_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_checkout_real', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estado', sa.Enum('RESERVADA', 'CHECK_IN', 'CHECK_OUT', 'CANCELADA', name='estado_reserva', native_enum=False), server_default='RESERVADA', nullable=False),
    sa.Column('origen', sa.String(length=20), server_default=sa.text("'DIRECTO'"), nullable=False),
    sa.Column('referencia_externa', sa.String(length=255), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['hotel.usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_habitacion'], ['hotel.habitacion.id_habitacion'], ),
    sa.ForeignKeyConstraint(['id_huesped'], ['hotel.huesped.id_huesped'], ),
    sa.PrimaryKeyConstraint('id_reserva'),
    schema='hotel'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reserva', schema='hotel')
    op.drop_index(op.f('ix_hotel_huesped_cedula'), table_name='huesped', schema='hotel')
    op.drop_table('huesped', schema='hotel')
    op.drop_index(op.f('ix_hotel_habitacion_numero'), table_name='habitacion', schema='hotel')
    op.drop_table('habitacion', schema='hotel')
    # ### end Alembic commands ###
