"""restaurante: mesa, pedido, pedido_item

Revision ID: 1cfc5ecc8068
Revises: 30883ff2f000
Create Date: 2026-08-07 09:48:38.339538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cfc5ecc8068'
down_revision: Union[str, None] = '30883ff2f000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mesa',
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('capacidad', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Float(), server_default=sa.text('50'), nullable=False),
    sa.Column('pos_y', sa.Float(), server_default=sa.text('50'), nullable=False),
    sa.Column('estado', sa.Enum('LIBRE', 'OCUPADA', name='estado_mesa', native_enum=False), server_default='LIBRE', nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_mesa'),
    schema='hotel'
    )
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_mesa', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'ENVIADO_COCINA', 'EN_PREPARACION', 'LISTO', 'ENTREGADO', 'CERRADO', name='estado_pedido', native_enum=False), server_default='ABIERTO', nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('enviado_cocina_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cerrado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['hotel.usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_mesa'], ['hotel.mesa.id_mesa'], ),
    sa.PrimaryKeyConstraint('id_pedido'),
    schema='hotel'
    )
    op.create_table('pedido_item',
    sa.Column('id_item', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('nota', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['hotel.pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['hotel.producto_restaurante.id_producto'], ),
    sa.PrimaryKeyConstraint('id_item'),
    schema='hotel'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido_item', schema='hotel')
    op.drop_table('pedido', schema='hotel')
    op.drop_table('mesa', schema='hotel')
    # ### end Alembic commands ###
