"""productos: producto_restaurante, producto_bar

Revision ID: 30883ff2f000
Revises: 30d9b51e8873
Create Date: 2026-08-07 08:59:36.642182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30883ff2f000'
down_revision: Union[str, None] = '30d9b51e8873'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto_bar',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('codigo_barras', sa.String(length=50), nullable=False),
    sa.Column('precio_costo', sa.Integer(), nullable=False),
    sa.Column('precio_venta', sa.Integer(), nullable=False),
    sa.Column('stock', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_producto'),
    schema='hotel'
    )
    op.create_index(op.f('ix_hotel_producto_bar_codigo_barras'), 'producto_bar', ['codigo_barras'], unique=True, schema='hotel')
    op.create_table('producto_restaurante',
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('precio_venta', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_producto'),
    schema='hotel'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto_restaurante', schema='hotel')
    op.drop_index(op.f('ix_hotel_producto_bar_codigo_barras'), table_name='producto_bar', schema='hotel')
    op.drop_table('producto_bar', schema='hotel')
    # ### end Alembic commands ###
