"""tarifas: temporada, precio_total en reserva

Revision ID: 30d9b51e8873
Revises: 0d808265c773
Create Date: 2026-08-06 20:44:58.091281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d9b51e8873'
down_revision: Union[str, None] = '0d808265c773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporada',
    sa.Column('id_temporada', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('precio_noche', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_temporada'),
    schema='hotel'
    )
    op.add_column(
        'reserva',
        sa.Column('precio_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
        schema='hotel',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reserva', 'precio_total', schema='hotel')
    op.drop_table('temporada', schema='hotel')
    # ### end Alembic commands ###
