"""consumo: consumo_item

Revision ID: 4a65133119d5
Revises: 1cfc5ecc8068
Create Date: 2026-08-07 10:09:19.169268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a65133119d5'
down_revision: Union[str, None] = '1cfc5ecc8068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumo_item',
    sa.Column('id_consumo', sa.Integer(), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=False),
    sa.Column('origen', sa.Enum('BAR', 'RESTAURANTE', name='origen_consumo', native_enum=False), nullable=False),
    sa.Column('id_producto_bar', sa.Integer(), nullable=True),
    sa.Column('id_producto_restaurante', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['hotel.usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_producto_bar'], ['hotel.producto_bar.id_producto'], ),
    sa.ForeignKeyConstraint(['id_producto_restaurante'], ['hotel.producto_restaurante.id_producto'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['hotel.reserva.id_reserva'], ),
    sa.PrimaryKeyConstraint('id_consumo'),
    schema='hotel'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consumo_item', schema='hotel')
    # ### end Alembic commands ###
