"""caja_turno_venta_gasto

Revision ID: aec004432553
Revises: 4a65133119d5
Create Date: 2026-08-07 10:33:03.576432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec004432553'
down_revision: Union[str, None] = '4a65133119d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turno_caja',
    sa.Column('id_turno', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('ABIERTO', 'CERRADO', name='estado_turno_caja', native_enum=False), server_default='ABIERTO', nullable=False),
    sa.Column('monto_apertura', sa.Integer(), nullable=False),
    sa.Column('monto_cierre_real', sa.Integer(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario'], ['hotel.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_turno'),
    schema='hotel'
    )
    op.create_table('gasto',
    sa.Column('id_gasto', sa.Integer(), nullable=False),
    sa.Column('id_turno_caja', sa.Integer(), nullable=False),
    sa.Column('concepto', sa.String(length=255), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['hotel.usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_turno_caja'], ['hotel.turno_caja.id_turno'], ),
    sa.PrimaryKeyConstraint('id_gasto'),
    schema='hotel'
    )
    op.create_table('venta',
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_turno_caja', sa.Integer(), nullable=False),
    sa.Column('origen', sa.Enum('HABITACION', 'MESA', 'MOSTRADOR', name='origen_venta', native_enum=False), nullable=False),
    sa.Column('id_reserva', sa.Integer(), nullable=True),
    sa.Column('id_pedido', sa.Integer(), nullable=True),
    sa.Column('metodo_pago', sa.Enum('EFECTIVO', 'TARJETA', 'TRANSFERENCIA', 'QR', name='metodo_pago', native_enum=False), nullable=False),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creado_por'], ['hotel.usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['hotel.pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_reserva'], ['hotel.reserva.id_reserva'], ),
    sa.ForeignKeyConstraint(['id_turno_caja'], ['hotel.turno_caja.id_turno'], ),
    sa.PrimaryKeyConstraint('id_venta'),
    schema='hotel'
    )
    op.create_table('venta_item',
    sa.Column('id_venta_item', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_producto_bar', sa.Integer(), nullable=True),
    sa.Column('id_producto_restaurante', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_producto_bar'], ['hotel.producto_bar.id_producto'], ),
    sa.ForeignKeyConstraint(['id_producto_restaurante'], ['hotel.producto_restaurante.id_producto'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['hotel.venta.id_venta'], ),
    sa.PrimaryKeyConstraint('id_venta_item'),
    schema='hotel'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venta_item', schema='hotel')
    op.drop_table('venta', schema='hotel')
    op.drop_table('gasto', schema='hotel')
    op.drop_table('turno_caja', schema='hotel')
    # ### end Alembic commands ###
