"""auth: usuario, rol, permiso, recurso

Revision ID: d4281ab405f0
Revises: 
Create Date: 2026-08-05 21:52:49.527567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4281ab405f0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurso',
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_recurso'),
    sa.UniqueConstraint('codigo'),
    schema='hotel'
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('codigo'),
    schema='hotel'
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_usuario'),
    schema='hotel'
    )
    op.create_index(op.f('ix_hotel_usuario_email'), 'usuario', ['email'], unique=True, schema='hotel')
    op.create_table('permiso',
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.Column('id_recurso', sa.Integer(), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id_recurso'], ['hotel.recurso.id_recurso'], ),
    sa.PrimaryKeyConstraint('id_permiso'),
    sa.UniqueConstraint('id_recurso', 'accion'),
    schema='hotel'
    )
    op.create_table('usuario_rol',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('asignado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('asignado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asignado_por'], ['hotel.usuario.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['hotel.rol.id_rol'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['hotel.usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario', 'id_rol'),
    schema='hotel'
    )
    op.create_table('rol_permiso',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['hotel.permiso.id_permiso'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['hotel.rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso'),
    schema='hotel'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rol_permiso', schema='hotel')
    op.drop_table('usuario_rol', schema='hotel')
    op.drop_table('permiso', schema='hotel')
    op.drop_index(op.f('ix_hotel_usuario_email'), table_name='usuario', schema='hotel')
    op.drop_table('usuario', schema='hotel')
    op.drop_table('rol', schema='hotel')
    op.drop_table('recurso', schema='hotel')
    # ### end Alembic commands ###
